"""Observer system for AXIOM — detects behavioral patterns and generates suggestions.

Analyzes persistent action history to identify repeating patterns and offers
proactive suggestions. All suggestions are advisory — the agent NEVER acts
automatically.

Architecture:
- PatternDetector: abstract base for detection strategies (pluggable)
- Observer: orchestrates detectors, deduplicates suggestions per session
- Built-in: FrequencyDetector, TemporalDetector
- Extend: observer.register(MyDetector()) at runtime
"""

import re
import time
from abc import ABC, abstractmethod
from collections import Counter, defaultdict
from datetime import datetime
from typing import List, Dict, Optional, NamedTuple

from utils.logger import get_logger
from utils.config import get_config

logger = get_logger(__name__)


# ------------------------------------------------------------------
# Data structures
# ------------------------------------------------------------------

class Suggestion(NamedTuple):
    """A proactive suggestion generated by a pattern detector."""
    pattern_id: str       # Unique key for dedup (e.g., "freq:open_app:firefox")
    message: str          # Human-readable suggestion
    confidence: float     # 0.0–1.0
    action: str           # Related action name
    params: str           # Related params


# ------------------------------------------------------------------
# Abstract detector
# ------------------------------------------------------------------

class PatternDetector(ABC):
    """Base class for pattern detection strategies.

    Subclass and implement ``detect()`` to add new pattern types.
    Register with ``observer.register(instance)``.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable detector name."""
        ...

    @abstractmethod
    def detect(self, actions: List[Dict]) -> List[Suggestion]:
        """Analyze *actions* and return suggestions (may be empty).

        Each action dict has keys: action, params, ok, message, timestamp.
        """
        ...


# ------------------------------------------------------------------
# Built-in detectors
# ------------------------------------------------------------------

class FrequencyDetector(PatternDetector):
    """Detects the same (action, params) repeated ≥ *threshold* times
    within *window_hours*."""

    def __init__(self, threshold: int = 3, window_hours: int = 24):
        self.threshold = threshold
        self.window_hours = window_hours

    @property
    def name(self) -> str:
        return "frequency"

    def detect(self, actions: List[Dict]) -> List[Suggestion]:
        cutoff = time.time() - self.window_hours * 3600
        recent = [a for a in actions
                  if a.get('timestamp', 0) >= cutoff and a.get('ok')]

        counts: Counter = Counter()
        for a in recent:
            counts[(a['action'], a.get('params', ''))] += 1

        suggestions = []
        for (action, params), count in counts.items():
            if count >= self.threshold:
                readable = _extract_readable_param(params) or action
                suggestions.append(Suggestion(
                    pattern_id=f"freq:{action}:{readable}",
                    message=(f"You've used '{readable}' ({action}) {count} times "
                             f"in the last {self.window_hours}h. "
                             f"Want me to automate this?"),
                    confidence=min(count / (self.threshold * 2), 1.0),
                    action=action,
                    params=params,
                ))
        return suggestions


class TemporalDetector(PatternDetector):
    """Detects actions occurring at similar times across ≥ *min_days* days."""

    def __init__(self, min_days: int = 2, time_tolerance_minutes: int = 30):
        self.min_days = min_days
        self.tolerance = time_tolerance_minutes

    @property
    def name(self) -> str:
        return "temporal"

    def detect(self, actions: List[Dict]) -> List[Suggestion]:
        # Group by (action, params) → timestamps
        by_key: Dict[tuple, List[float]] = defaultdict(list)
        for a in actions:
            if a.get('ok'):
                by_key[(a['action'], a.get('params', ''))].append(a['timestamp'])

        suggestions = []
        for (action, params), timestamps in by_key.items():
            result = self._find_daily_pattern(timestamps)
            if result:
                hour, minute, day_count = result
                readable = _extract_readable_param(params) or action
                time_str = f"{hour:02d}:{minute:02d}"
                suggestions.append(Suggestion(
                    pattern_id=f"temporal:{action}:{readable}:{time_str}",
                    message=(f"I noticed you use '{readable}' around {time_str} "
                             f"on {day_count} different days. "
                             f"Want me to automate this?"),
                    confidence=min(day_count / (self.min_days * 2), 1.0),
                    action=action,
                    params=params,
                ))
        return suggestions

    def _find_daily_pattern(self, timestamps: List[float]) -> Optional[tuple]:
        """Return (hour, minute, day_count) if timestamps cluster around the
        same time-of-day across multiple calendar days, else None."""
        if len(timestamps) < self.min_days:
            return None

        # One entry per calendar day (keep first occurrence)
        by_date: Dict = {}
        for ts in timestamps:
            dt = datetime.fromtimestamp(ts)
            if dt.date() not in by_date:
                by_date[dt.date()] = (dt.hour, dt.minute)

        if len(by_date) < self.min_days:
            return None

        # Check clustering around the median time
        mins = sorted(h * 60 + m for h, m in by_date.values())
        median = mins[len(mins) // 2]
        matching = sum(1 for t in mins if abs(t - median) <= self.tolerance)

        if matching >= self.min_days:
            return (median // 60, median % 60, matching)
        return None


# ------------------------------------------------------------------
# Observer orchestrator
# ------------------------------------------------------------------

class Observer:
    """Runs all registered detectors and deduplicates suggestions per session."""

    def __init__(self):
        self.detectors: List[PatternDetector] = []
        self._seen: set = set()          # pattern_ids already shown this session
        self._register_defaults()

    def _register_defaults(self) -> None:
        cfg = get_config() or {}
        obs = cfg.get('observer', {})
        self.register(FrequencyDetector(
            threshold=obs.get('frequency_threshold', 3),
            window_hours=obs.get('frequency_window_hours', 24),
        ))
        self.register(TemporalDetector(
            min_days=obs.get('temporal_min_days', 2),
            time_tolerance_minutes=obs.get('temporal_tolerance_minutes', 30),
        ))

    def register(self, detector: PatternDetector) -> None:
        """Add a pattern detector."""
        self.detectors.append(detector)
        logger.debug("Registered detector: %s", detector.name)

    def check(self, lookback: int = 50) -> List[Suggestion]:
        """Run detectors and return *new* (not-yet-shown) suggestions."""
        from brain.persistent_memory import get_persistent_memory
        actions = get_persistent_memory().get_recent(lookback)
        if not actions:
            return []

        all_suggestions: List[Suggestion] = []
        for det in self.detectors:
            try:
                all_suggestions.extend(det.detect(actions))
            except Exception as e:
                logger.error("Detector '%s' failed: %s", det.name, e)

        new = [s for s in all_suggestions if s.pattern_id not in self._seen]
        for s in new:
            self._seen.add(s.pattern_id)

        new.sort(key=lambda s: s.confidence, reverse=True)
        return new

    def reset_seen(self) -> None:
        """Clear seen-suggestions (e.g., at session start)."""
        self._seen.clear()


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _extract_readable_param(params: str) -> Optional[str]:
    """Pull the most meaningful value from a key=\"value\" param string."""
    if not params:
        return None
    m = re.search(r'(?:name|path|cmd|text|query)="([^"]+)"', params)
    if m:
        return m.group(1)
    m = re.search(r'"([^"]+)"', params)
    if m:
        return m.group(1)
    return params.strip() or None


# ------------------------------------------------------------------
# Global singleton
# ------------------------------------------------------------------

_instance: Optional[Observer] = None


def get_observer() -> Observer:
    """Get or create the global Observer instance."""
    global _instance
    if _instance is None:
        _instance = Observer()
    return _instance
